Repository Leafwing-Studios/leafwing-input-manager, pull requests merged in 2022-11, with the labels that each got.

#282 Custom serde implementation for `InputMap`
  Cargo.toml
  RELEASES.md
  src/input_map.rs
Labels: usability

#283 Ignore keyboard and mouse if egui uses them
  Cargo.toml
  RELEASES.md
  examples/binding_menu.rs
  src/input_mocking.rs
  src/input_streams.rs
  src/systems.rs
Labels: usability

#284 Update for Bevy 0.9 and release 0.7
  Cargo.toml
  README.md
  RELEASES.md
  examples/arpg_indirection.rs
  examples/axis_inputs.rs
  examples/binding_menu.rs
  examples/clash_handling.rs
  examples/consuming_actions.rs
  examples/minimal.rs
  examples/mouse_motion.rs
  examples/mouse_wheel.rs
  examples/multiplayer.rs
  examples/press_duration.rs
  examples/send_actions_over_network.rs
  examples/single_player.rs
  examples/ui_driven_actions.rs
  examples/virtual_dpad.rs
  macros/Cargo.toml
  src/action_state.rs
  src/clashing_inputs.rs
  src/input_map.rs
  src/input_mocking.rs
  src/input_streams.rs
  src/plugin.rs
  src/systems.rs
  tests/clashes.rs
  tests/gamepad_axis.rs
  tests/integration.rs
Labels: dependencies, release

#290 Fix clicking through egui widgets
  src/systems.rs
Labels: bug
