Repository Leafwing-Studios/leafwing-input-manager, pull requests merged in 2022-10, with the labels that each got.

#253 Store per-action cooldowns
  RELEASES.md
  src/action_state.rs
  src/cooldown.rs
  src/lib.rs
  src/user_input.rs
Labels: enhancement

#261 Store Cooldowns in a component
  RELEASES.md
  examples/arpg_indirection.rs
  examples/axis_inputs.rs
  examples/minimal.rs
  examples/mouse_motion.rs
  examples/mouse_wheel.rs
  examples/press_duration.rs
  examples/send_actions_over_network.rs
  examples/single_player.rs
  examples/virtual_dpad.rs
  src/action_state.rs
  src/cooldown.rs
  src/lib.rs
  src/plugin.rs
  src/systems.rs
  tests/cooldowns.rs
Labels: usability

#264 Add `with_deadzone` setters for axes
  RELEASES.md
  src/axislike.rs
Labels: usability

#262 Add global cooldowns
  src/cooldown.rs
  tests/cooldowns.rs
Labels: enhancement

#267 Add direct support for modifier keys
  RELEASES.md
  src/display_impl.rs
  src/input_map.rs
  src/input_streams.rs
  src/lib.rs
  src/user_input.rs
Labels: usability, breaking-change

#263 Release 0.6
  .github/workflows/ci.yml
  Cargo.toml
  RELEASES.md
  examples/arpg_indirection.rs
  examples/axis_inputs.rs
  examples/minimal.rs
  examples/mouse_motion.rs
  examples/mouse_wheel.rs
  examples/press_duration.rs
  examples/send_actions_over_network.rs
  examples/single_player.rs
  examples/virtual_dpad.rs
  src/action_state.rs
  src/axislike.rs
  src/clashing_inputs.rs
  src/cooldown.rs
  src/display_impl.rs
  src/input_map.rs
  src/input_streams.rs
  src/lib.rs
  src/plugin.rs
  src/systems.rs
  src/user_input.rs
  tests/cooldowns.rs
  tests/integration.rs
  tools/ci/src/main.rs
Labels: release

#271 Add crates.io badge to readme
  README.md
Labels: meta

#272 Split cooldowns and charges
  RELEASES.md
  examples/binding_menu.rs
  examples/consuming_actions.rs
  examples/minimal.rs
  src/charges.rs
  src/cooldown.rs
  src/lib.rs
  src/systems.rs
  tests/actionlike_derive.rs
  tests/cooldowns.rs
Labels: code-quality, usability

#274 Swap to 0.5.2: no breaking changes
  Cargo.toml
  macros/Cargo.toml
Labels: release

#273 Remove cooldowns and charges code
  README.md
  RELEASES.md
  examples/axis_inputs.rs
  examples/minimal.rs
  src/charges.rs
  src/cooldown.rs
  src/lib.rs
  src/plugin.rs
  src/systems.rs
  tests/cooldowns.rs
Labels: code-quality, meta

#275 Prepare for 0.6 release
  Cargo.toml
Labels: release

#277 Add VirtualAxis
  RELEASES.md
  src/axislike.rs
  src/clashing_inputs.rs
  src/display_impl.rs
  src/input_streams.rs
  src/user_input.rs
Labels: usability
