Repository Leafwing-Studios/leafwing-input-manager, pull requests merged in 2022-12, with the labels that each got.

#291 Only deal with egui if the resource exists
  src/systems.rs
Labels: bug, usability

#292 Prepare for 0.7.1 release
  Cargo.toml
  RELEASES.md
Labels: release

#296 Update egui and setup dependabot
  .github/dependabot.yml
  Cargo.toml
Labels: build system, dependencies
