Repository Leafwing-Studios/leafwing-input-manager, pull requests merged in 2022-07, with the labels that each got.

#129 Fix broken duration pressed functionality
  Cargo.toml
  RELEASES.md
  examples/press_duration.rs
  src/action_state.rs
  src/systems.rs
  tests/integration.rs
Labels: bug

#152 Reverse order of `InputMap` from `(action, input)` to `(input, action)`
  README.md
  RELEASES.md
  examples/arpg_indirection.rs
  examples/binding_menu.rs
  examples/clash_handling.rs
  examples/consuming_actions.rs
  examples/minimal.rs
  examples/multiplayer.rs
  examples/press_duration.rs
  examples/send_actions_over_network.rs
  examples/single_player.rs
  examples/ui_driven_actions.rs
  src/action_state.rs
  src/clashing_inputs.rs
  src/input_map.rs
  tests/clashes.rs
  tests/integration.rs
Labels: usability, breaking-change

#141 Release 0.4
  .github/workflows/ci.yml
  Cargo.toml
  README.md
  RELEASES.md
  examples/arpg_indirection.rs
  examples/binding_menu.rs
  examples/clash_handling.rs
  examples/consuming_actions.rs
  examples/minimal.rs
  examples/multiplayer.rs
  examples/press_duration.rs
  examples/send_actions_over_network.rs
  examples/single_player.rs
  examples/ui_driven_actions.rs
  src/action_state.rs
  src/clashing_inputs.rs
  src/input_map.rs
  src/plugin.rs
  src/systems.rs
  tests/clashes.rs
  tests/integration.rs
Labels: meta

#151 Add Support For Gamepad Axes
  README.md
  RELEASES.md
  examples/axis_inputs.rs
  examples/binding_menu.rs
  examples/virtual_dpad.rs
  src/action_state.rs
  src/axislike.rs
  src/clashing_inputs.rs
  src/display_impl.rs
  src/input_map.rs
  src/input_mocking.rs
  src/lib.rs
  src/systems.rs
  src/user_input.rs
Labels: enhancement

#161 sync up macros dependency with macros crate name
  Cargo.toml
  RELEASES.md
Labels: bug

#162 Fix conflict between macro crate name and version
  Cargo.toml
  RELEASES.md
  macros/Cargo.toml
Labels: bug, build system

#163 Merge changes from main into dev branch
  Cargo.toml
  RELEASES.md
  macros/Cargo.toml
Labels: release

#165 Add builder methods for new axislike input types
  examples/axis_inputs.rs
  src/action_state.rs
  src/axislike.rs
  src/clashing_inputs.rs
  src/display_impl.rs
  src/lib.rs
  src/user_input.rs
Labels: usability

#167 Remove ActionState::reasons_pressed API
  RELEASES.md
  src/action_state.rs
  src/input_map.rs
  tests/integration.rs
Labels: usability

#168 Scan all gamepads for inputs if none is registered
  RELEASES.md
  examples/axis_inputs.rs
  examples/multiplayer.rs
  examples/single_player.rs
  src/input_map.rs
  src/input_mocking.rs
  src/systems.rs
  src/user_input.rs
Labels: usability

#170 Update to Bevy 0.8-dev
  Cargo.toml
  examples/binding_menu.rs
  examples/multiplayer.rs
  examples/press_duration.rs
  examples/ui_driven_actions.rs
  src/axislike.rs
  src/input_map.rs
  src/input_mocking.rs
  src/orientation.rs
  src/systems.rs
  src/user_input.rs
Labels: release

#171 Set axis values when mocking user input
  src/action_state.rs
  src/axislike.rs
  src/input_mocking.rs
  src/user_input.rs
Labels: enhancement

#172 Fix broken dependencies induced by merge conflict resolution
  Cargo.toml
  src/input_map.rs
Labels: bug, build system

#176 Cleanup old TODO and FIXME comments
  RELEASES.md
  src/action_state.rs
  src/axislike.rs
  src/clashing_inputs.rs
  src/orientation.rs
Labels: code-quality

#180 Support Single Axis Inputs in Virtual DPads
  Cargo.toml
  examples/axis_inputs.rs
  examples/binding_menu.rs
  src/action_state.rs
  src/axislike.rs
  src/input_map.rs
  src/input_streams.rs
Labels: bug

#186 Add mouse motion support
  RELEASES.md
  examples/mouse_motion.rs
  src/axislike.rs
  src/buttonlike.rs
  src/display_impl.rs
  src/input_map.rs
  src/input_mocking.rs
  src/input_streams.rs
  src/orientation.rs
  src/systems.rs
  src/user_input.rs
Labels: enhancement

#187 Depend on Bevy directly
  Cargo.toml
  examples/arpg_indirection.rs
  examples/consuming_actions.rs
  examples/send_actions_over_network.rs
  examples/ui_driven_actions.rs
  src/action_state.rs
  src/axislike.rs
  src/buttonlike.rs
  src/clashing_inputs.rs
  src/errors.rs
  src/input_map.rs
  src/input_mocking.rs
  src/input_streams.rs
  src/lib.rs
  src/orientation.rs
  src/plugin.rs
  src/systems.rs
  src/user_input.rs
  tests/clashes.rs
  tests/integration.rs
  tests/mouse_wheel.rs
Labels: code-quality

#192 Bump to Bevy 0.8
  Cargo.toml
  examples/binding_menu.rs
Labels: dependencies

#193 Make input stream fields non-optional
  RELEASES.md
  examples/send_actions_over_network.rs
  src/action_state.rs
  src/clashing_inputs.rs
  src/input_map.rs
  src/input_mocking.rs
  src/input_streams.rs
  src/lib.rs
  src/systems.rs
  tests/clashes.rs
  tests/integration.rs
  tests/mouse_wheel.rs
Labels: code-quality, usability

#194 Clean up input mocking code
  RELEASE-CHECKLIST.md
  RELEASES.md
  src/input_map.rs
  src/input_mocking.rs
  src/input_streams.rs
Labels: code-quality, usability

#197 Add tests for decomposing `UserInput` into raw inputs
  RELEASE-CHECKLIST.md
  RELEASES.md
  src/input_mocking.rs
  src/user_input.rs
Labels: code-quality
