Repository Leafwing-Studios/leafwing-input-manager, pull requests merged in 2022-08, with the labels that each got.

#207 Mocking inputs now sends raw events
  Cargo.toml
  RELEASES.md
  src/action_state.rs
  src/clashing_inputs.rs
  src/input_map.rs
  src/input_mocking.rs
  src/input_streams.rs
  src/systems.rs
  tests/clashes.rs
  tests/gamepad_axis.rs
Labels: bug

#206 Minor documentation fix, s/pressed/released/
  src/action_state.rs
Labels: documentation

#164 Release 0.5
  Cargo.toml
  README.md
  RELEASE-CHECKLIST.md
  RELEASES.md
  examples/arpg_indirection.rs
  examples/axis_inputs.rs
  examples/binding_menu.rs
  examples/consuming_actions.rs
  examples/mouse_motion.rs
  examples/mouse_wheel.rs
  examples/multiplayer.rs
  examples/press_duration.rs
  examples/send_actions_over_network.rs
  examples/single_player.rs
  examples/ui_driven_actions.rs
  examples/virtual_dpad.rs
  macros/Cargo.toml
  src/action_state.rs
  src/axislike.rs
  src/buttonlike.rs
  src/clashing_inputs.rs
  src/display_impl.rs
  src/errors.rs
  src/input_map.rs
  src/input_mocking.rs
  src/input_streams.rs
  src/lib.rs
  src/orientation.rs
  src/plugin.rs
  src/systems.rs
  src/user_input.rs
  tests/clashes.rs
  tests/gamepad_axis.rs
  tests/integration.rs
  tests/mouse_motion.rs
  tests/mouse_wheel.rs
Labels: release

#209 Fix crate name in Cargo.toml
  Cargo.toml
Labels: bug

#212 Typo fix in release notes
  RELEASES.md
Labels: documentation

#220 Bump version number to 0.5.1
  Cargo.toml
  RELEASES.md
Labels: bug, meta

#228 Improve ToggleActions
  RELEASES.md
  src/plugin.rs
Labels: usability

#214 Add `ActionState::action_data_mut` for retrieving mutable state for an action
  src/action_state.rs
Labels: good first issue, usability

#236 Fix clippy warnings to also derive `Eq`
  RELEASES.md
  src/action_state.rs
  src/input_map.rs
Labels: usability

#235 Run `cargo check` with no features and default features in CI
  tools/ci/src/main.rs
Labels: build system

#232 Make Sure Gampad Axis Value Is Within Deadzone
  Cargo.toml
  RELEASES.md
  src/action_state.rs
  src/input_map.rs
  src/input_streams.rs
Labels: bug

#234 Run clippy on examples in CI
  tools/ci/src/main.rs
Labels: build system

#233 Change CI workflow to run on ubuntu-latest
  .github/workflows/ci.yml
Labels: build system
