Repository Leafwing-Studios/leafwing-input-manager, pull requests merged in 2023-03, with the labels that each got.

#312 Add support for scancode keyboard input
  examples/physical_key_bindings.rs
  src/axislike.rs
  src/display_impl.rs
  src/input_streams.rs
  src/lib.rs
  src/scan_codes/linux.rs
  src/scan_codes/mac_os.rs
  src/scan_codes/mod.rs
  src/scan_codes/wasm.rs
  src/scan_codes/windows.rs
  src/systems.rs
  src/user_input.rs
Labels: enhancement

#317 Update to Bevy 0.10
  Cargo.toml
  RELEASES.md
  examples/arpg_indirection.rs
  examples/binding_menu.rs
  examples/press_duration.rs
  examples/send_actions_over_network.rs
  examples/ui_driven_actions.rs
  src/input_mocking.rs
  src/input_streams.rs
  src/plugin.rs
  src/systems.rs
  tests/gamepad_axis.rs
  tests/integration.rs
Labels: dependencies

#326 Prepare release 0.9
  Cargo.toml
  RELEASES.md
  macros/Cargo.toml
Labels: release

#332 Add basic benchmarks
  Cargo.toml
  benches/action_state.rs
  benches/input_map.rs
  src/clashing_inputs.rs
Labels: performance, build system

#333 Use a faster, cached CI setup
  .github/workflows/ci.yml
  examples/virtual_dpad.rs
  macros/src/actionlike.rs
  macros/src/lib.rs
  src/action_state.rs
  src/axislike.rs
  src/buttonlike.rs
  src/errors.rs
  src/input_map.rs
  src/input_mocking.rs
  src/lib.rs
  src/orientation.rs
  src/plugin.rs
  src/press_scheduler.rs
  src/systems.rs
  src/user_input.rs
  tools/ci/Cargo.toml
  tools/ci/src/main.rs
Labels: build system
