Repository Leafwing-Studios/leafwing-input-manager, pull requests merged in 2023-08, with the labels that each got.

#371 examples: Move update_cursor_state_from_window to Update
  examples/mouse_position.rs
Labels: example

#370 Deadzone shapes
  RELEASES.md
  src/axislike.rs
  src/input_map.rs
  src/input_streams.rs
  src/lib.rs
  src/user_input.rs
  tests/gamepad_axis.rs
  tests/mouse_motion.rs
  tests/mouse_wheel.rs
Labels: enhancement, breaking-change

#377 Add sensitivity
  RELEASES.md
  src/axislike.rs
  src/input_map.rs
  src/input_streams.rs
  tests/gamepad_axis.rs
  tests/mouse_motion.rs
  tests/mouse_wheel.rs
Labels: enhancement, controversial
