Repository Leafwing-Studios/leafwing-input-manager, pull requests merged in 2024-12, with the labels that each got.

#663 registries: no need for `static mut` or unsafe + use std's LazyLock
  Cargo.toml
  macros/src/actionlike.rs
  src/input_processing/dual_axis/custom.rs
  src/input_processing/single_axis/custom.rs
  src/user_input/trait_serde.rs
Labels: code-quality

#662 Make the macros deterministic, using BTreeMap instead of HashMap
  macros/src/actionlike.rs
Labels: bug

#666 Fix ignored tests from update to bevy 0.15
  tests/buttonlike.rs
Labels: bug

#667 Prepare for 0.16 release
  Cargo.toml
  README.md
  RELEASES.md
  macros/Cargo.toml
Labels: release
