Repository Leafwing-Studios/leafwing-input-manager, pull requests merged in 2024-10, with the labels that each got.

#640 Prepare 0.15.1 release
  Cargo.toml
  macros/Cargo.toml
Labels: release

#637 Add wasm32 build to ci (#636)
  .cargo/config.toml
  .github/workflows/ci.yml
  Cargo.toml
  tools/ci/src/main.rs
Labels: build system, breaking-change

#624 Add `threshold` value for `GamepadControlDirection`, `MouseMoveDirection`, and `MouseScrollDirection`
  RELEASES.md
  src/axislike.rs
  src/user_input/gamepad.rs
  src/user_input/mouse.rs
Labels: usability, breaking-change

#623 Make virtual axial controls more flexible, accepting any kind of `Buttonlike`
  RELEASES.md
  examples/action_state_resource.rs
  examples/default_controls.rs
  examples/input_processing.rs
  examples/twin_stick_controller.rs
  examples/virtual_dpad.rs
  src/clashing_inputs.rs
  src/input_map.rs
  src/plugin.rs
  src/user_input/gamepad.rs
  src/user_input/keyboard.rs
  src/user_input/mod.rs
  src/user_input/trait_serde.rs
  src/user_input/virtual_axial.rs
  tests/gamepad_axis.rs
Labels: usability, breaking-change

#601 Add ability to filter entities for which action diffs should be generated
  RELEASES.md
  src/action_diff.rs
  src/systems.rs
  tests/action_diffs.rs
Labels: usability, breaking-change
