Repository Leafwing-Studios/leafwing-input-manager, pull requests merged in 2024-08, with the labels that each got.

#570 Move input mocking to new traits
  README.md
  RELEASE-CHECKLIST.md
  RELEASES.md
  benches/input_map.rs
  examples/send_actions_over_network.rs
  src/action_state/mod.rs
  src/clashing_inputs.rs
  src/input_mocking.rs
  src/input_streams.rs
  src/lib.rs
  src/raw_inputs.rs
  src/user_input/chord.rs
  src/user_input/gamepad.rs
  src/user_input/keyboard.rs
  src/user_input/mod.rs
  src/user_input/mouse.rs
  src/user_input/testing_utils.rs
  tests/clashes.rs
  tests/fixed_update.rs
  tests/gamepad_axis.rs
  tests/integration.rs
  tests/mouse_motion.rs
  tests/mouse_wheel.rs
Labels: code-quality, usability

#574 Fix virtual_dpad example
  examples/virtual_dpad.rs
Labels: example

#576 Remove `InputStreams` using a subtrait of `UserInput`, allowing users to add their own input kinds
  RELEASES.md
  benches/input_map.rs
  src/action_state/action_data.rs
  src/action_state/mod.rs
  src/clashing_inputs.rs
  src/input_map.rs
  src/input_streams.rs
  src/lib.rs
  src/plugin.rs
  src/systems.rs
  src/user_input/chord.rs
  src/user_input/gamepad.rs
  src/user_input/keyboard.rs
  src/user_input/mod.rs
  src/user_input/mouse.rs
  src/user_input/testing_utils.rs
  src/user_input/updating.rs
  tests/clashes.rs
  tests/multiple_gamepads.rs
Labels: enhancement, code-quality

#580 Fix action diffing
  RELEASES.md
  src/action_diff.rs
  src/action_state/mod.rs
  src/systems.rs
  tests/action_diffs.rs
Labels: bug, code-quality

#582 Remove action consuming
  RELEASES.md
  examples/consuming_actions.rs
  src/action_state/action_data.rs
  src/action_state/mod.rs
  tests/fixed_update.rs
Labels: code-quality, usability

#584 Bump to version 0.15
  Cargo.toml
  RELEASES.md
Labels: release

#590 Fixes #589: compilation for target wasm32-unknown-unknown
  src/action_state/action_data.rs
Labels: bug

#598 Implement MapEntities for ActionDiffEvent
  RELEASES.md
  src/action_diff.rs
Labels: usability

#603 Add `#[actionlike]` for actions to set their `InputControlKind`s
  RELEASES.md
  examples/axis_inputs.rs
  examples/default_controls.rs
  examples/input_processing.rs
  examples/mouse_motion.rs
  examples/mouse_wheel.rs
  examples/twin_stick_controller.rs
  examples/virtual_dpad.rs
  macros/src/actionlike.rs
  macros/src/lib.rs
  macros/src/typetag.rs
  src/action_diff.rs
  src/clashing_inputs.rs
  src/input_map.rs
  src/lib.rs
  tests/action_diffs.rs
  tests/gamepad_axis.rs
  tests/mouse_motion.rs
  tests/mouse_wheel.rs
Labels: usability

#607 Update outdated docs and simplify internal code
  src/action_diff.rs
  src/action_state/action_data.rs
  src/action_state/mod.rs
  src/input_map.rs
  src/lib.rs
  src/user_input/chord.rs
  src/user_input/gamepad.rs
  src/user_input/keyboard.rs
  src/user_input/mouse.rs
  src/user_input/trait_reflection.rs
  src/user_input/updating.rs
  tests/action_diffs.rs
Labels: documentation, code-quality

#608 Fix `InputMap::len` and add `InputMap::dual_axislike_mut` and missing registrations of chords
  src/input_map.rs
  src/plugin.rs
Labels: bug

#613 Fix buggy examples
  RELEASES.md
  examples/action_state_resource.rs
  examples/axis_inputs.rs
  examples/default_controls.rs
  examples/twin_stick_controller.rs
  examples/virtual_dpad.rs
  src/action_state/mod.rs
  src/input_map.rs
  src/user_input/mod.rs
Labels: bug, usability, example
