Repository Leafwing-Studios/leafwing-input-manager, pull requests merged in 2024-01, with the labels that each got.

#435 Update action-diff to not include the stable component ID
  examples/send_actions_over_network.rs
  src/action_state.rs
  src/systems.rs
  tests/action_diffs.rs
Labels: usability

#438 Accessible Deadzones
  RELEASES.md
  src/axislike.rs
  src/input_streams.rs
  tests/gamepad_axis.rs
  tests/mouse_motion.rs
  tests/mouse_wheel.rs
Labels: enhancement

#448 Pass actions by reference
  README.md
  RELEASES.md
  benches/action_state.rs
  examples/action_state_resource.rs
  examples/arpg_indirection.rs
  examples/axis_inputs.rs
  examples/clash_handling.rs
  examples/consuming_actions.rs
  examples/default_controls.rs
  examples/minimal.rs
  examples/mouse_motion.rs
  examples/mouse_position.rs
  examples/mouse_wheel.rs
  examples/physical_key_bindings.rs
  examples/press_duration.rs
  examples/register_gamepads.rs
  examples/send_actions_over_network.rs
  examples/single_player.rs
  examples/twin_stick_controller.rs
  examples/ui_driven_actions.rs
  examples/virtual_dpad.rs
  src/action_state.rs
  src/clashing_inputs.rs
  src/common_conditions.rs
  src/input_map.rs
  src/press_scheduler.rs
  src/systems.rs
  tests/action_diffs.rs
  tests/clashes.rs
  tests/gamepad_axis.rs
  tests/integration.rs
  tests/mouse_motion.rs
  tests/mouse_wheel.rs
Labels: code-quality

#449 Use (Action, Input) ordering for `InputMap` construction
  RELEASES.md
  benches/input_map.rs
  examples/action_state_resource.rs
  examples/arpg_indirection.rs
  examples/axis_inputs.rs
  examples/clash_handling.rs
  examples/consuming_actions.rs
  examples/default_controls.rs
  examples/minimal.rs
  examples/mouse_motion.rs
  examples/mouse_wheel.rs
  examples/multiplayer.rs
  examples/physical_key_bindings.rs
  examples/press_duration.rs
  examples/register_gamepads.rs
  examples/send_actions_over_network.rs
  examples/single_player.rs
  examples/twin_stick_controller.rs
  examples/ui_driven_actions.rs
  examples/virtual_dpad.rs
  src/action_state.rs
  src/clashing_inputs.rs
  src/input_map.rs
  tests/clashes.rs
  tests/gamepad_axis.rs
  tests/integration.rs
  tests/mouse_motion.rs
  tests/mouse_wheel.rs
Labels: usability, breaking-change

#450 Store a HashMap in `ActionState`
  RELEASES.md
  benches/action_state.rs
  benches/input_map.rs
  examples/arpg_indirection.rs
  examples/mouse_position.rs
  examples/twin_stick_controller.rs
  src/action_state.rs
  src/clashing_inputs.rs
  src/input_map.rs
  src/systems.rs
  tests/action_diffs.rs
  tests/clashes.rs
  tests/integration.rs
Labels: code-quality, breaking-change

#451 Remove `PressScheduler`
  RELEASES.md
  src/lib.rs
  src/press_scheduler.rs
  src/systems.rs
  tests/integration.rs
Labels: code-quality, breaking-change

#452 Remove methods from `Actionlike` to support more complex Action types
  RELEASES.md
  benches/action_state.rs
  examples/arpg_indirection.rs
  examples/clash_handling.rs
  examples/default_controls.rs
  examples/twin_stick_controller.rs
  macros/src/actionlike.rs
  src/action_state.rs
  src/clashing_inputs.rs
  src/input_map.rs
  src/lib.rs
  tests/actionlike_derive.rs
  tests/clashes.rs
  tests/mouse_motion.rs
  tests/mouse_wheel.rs
Labels: enhancement, breaking-change
