Repository Leafwing-Studios/leafwing-input-manager, pull requests merged in 2024-02, with the labels that each got.

#457 Fix incorrect `ActionData::axis_pair` value when handling multiple `DualAxisData`
  src/input_map.rs
Labels: bug

#462 Document crate feature flags in README and Cargo.toml
  Cargo.toml
  README.md
  RELEASES.md
Labels: documentation

#464 Release 0.12
  Cargo.toml
  RELEASES.md
  macros/Cargo.toml
Labels: release

#466 Refactor for clearer and more performant code
  src/action_state.rs
  src/axislike.rs
  src/clashing_inputs.rs
  src/display_impl.rs
  src/input_map.rs
  src/input_mocking.rs
  src/input_streams.rs
  src/orientation.rs
  src/systems.rs
  src/user_input.rs
  tests/action_diffs.rs
  tests/gamepad_axis.rs
Labels: code-quality

#460 Add docs.rs badge
  README.md
Labels: documentation

#472 Export `InputKind` in `prelude` module
  RELEASES.md
  src/lib.rs
Labels: usability

#473 Release the pressed `ActionData` when it isn't being updated
  RELEASES.md
  src/action_state.rs
Labels: bug

#474 Prefer `HashMap::values_mut()`
  src/action_state.rs
Labels: code-quality

#469 [Breaking Changes] Rename `Modifier::Win` to `Modifier::Super`
  RELEASES.md
  src/user_input.rs
Labels: usability, breaking-change

#470 Update for `bevy` 0.13 and `bevy_egui` 0.25
  Cargo.toml
  README.md
  RELEASES.md
  benches/input_map.rs
  examples/action_state_resource.rs
  examples/arpg_indirection.rs
  examples/clash_handling.rs
  examples/consuming_actions.rs
  examples/default_controls.rs
  examples/multiplayer.rs
  examples/physical_key_bindings.rs
  examples/press_duration.rs
  examples/register_gamepads.rs
  examples/send_actions_over_network.rs
  examples/single_player.rs
  examples/twin_stick_controller.rs
  examples/ui_driven_actions.rs
  examples/virtual_dpad.rs
  src/action_state.rs
  src/axislike.rs
  src/clashing_inputs.rs
  src/display_impl.rs
  src/input_map.rs
  src/input_mocking.rs
  src/input_streams.rs
  src/lib.rs
  src/plugin.rs
  src/scan_codes/linux.rs
  src/scan_codes/mac_os.rs
  src/scan_codes/mod.rs
  src/scan_codes/wasm.rs
  src/scan_codes/windows.rs
  src/systems.rs
  src/user_input.rs
  tests/clashes.rs
  tests/integration.rs
Labels: dependencies

#476 Improve clarity in the feature documentation
  Cargo.toml
Labels: documentation

#475 Add CI testing for all feature flag combinations and fix all reported errors
  tools/ci/Cargo.toml
  tools/ci/src/main.rs
Labels: build system

#477 Align the behavior of the `ui` feature with `egui`
  Cargo.toml
  README.md
  RELEASES.md
  src/systems.rs
  tools/ci/src/main.rs
Labels: usability, breaking-change

#479 Export `action_data_mut_or_default`
  src/action_state.rs
Labels: usability

#481 Const functions and cleanup
  RELEASES.md
  macros/src/lib.rs
  src/action_state.rs
  src/axislike.rs
  src/clashing_inputs.rs
  src/input_map.rs
  src/input_streams.rs
  src/orientation.rs
  src/systems.rs
  src/user_input.rs
Labels: code-quality, usability

#486 Apply suggestions from grammar check
  benches/input_map.rs
  examples/arpg_indirection.rs
  examples/axis_inputs.rs
  examples/consuming_actions.rs
  examples/mouse_wheel.rs
  examples/multiplayer.rs
  examples/register_gamepads.rs
  examples/send_actions_over_network.rs
  examples/twin_stick_controller.rs
  src/action_diff.rs
  src/action_driver.rs
  src/action_state.rs
  src/axislike.rs
  src/buttonlike.rs
  src/clashing_inputs.rs
  src/input_map.rs
  src/input_mocking.rs
  src/input_streams.rs
  src/orientation.rs
  src/plugin.rs
  src/systems.rs
  src/timing.rs
  src/user_input.rs
  tests/gamepad_axis.rs
  tests/integration.rs
  tests/mouse_motion.rs
  tests/mouse_wheel.rs
Labels: documentation

#489 Add `InputManagerBundle::with_map` and fix a mishandling of DualAxis
  README.md
  RELEASES.md
  examples/axis_inputs.rs
  examples/clash_handling.rs
  examples/default_controls.rs
  examples/minimal.rs
  examples/mouse_motion.rs
  examples/mouse_position.rs
  examples/mouse_wheel.rs
  examples/multiplayer.rs
  examples/press_duration.rs
  examples/register_gamepads.rs
  examples/send_actions_over_network.rs
  examples/single_player.rs
  examples/twin_stick_controller.rs
  examples/ui_driven_actions.rs
  examples/virtual_dpad.rs
  src/axislike.rs
  src/clashing_inputs.rs
  src/input_streams.rs
  src/lib.rs
  src/orientation.rs
  tests/integration.rs
Labels: bug, usability

#488 Remove Direction in favour of Direction2d from Bevy
  Cargo.toml
  RELEASES.md
  examples/single_player.rs
  src/axislike.rs
  src/orientation.rs
Labels: code-quality, usability, breaking-change
