Repository Leafwing-Studios/leafwing-input-manager, pull requests merged in 2024-06, with the labels that each got.

#456 Replace `ToggleActions<A>` with per-action disable flags
  RELEASES.md
  benches/action_state.rs
  src/action_state.rs
  src/lib.rs
  src/plugin.rs
  src/systems.rs
  tests/integration.rs
Labels: bug, usability, breaking-change

#530 Switch axis processing pipeline to `Vec`
  Cargo.toml
  RELEASES.md
  examples/input_processing.rs
  src/axislike.rs
  src/clashing_inputs.rs
  src/input_processing/dual_axis/mod.rs
  src/input_processing/mod.rs
  src/input_processing/single_axis/mod.rs
  tests/gamepad_axis.rs
Labels: code-quality

#533 Update `main` to Bevy 0.14 release candidate
  Cargo.toml
  benches/input_map.rs
  examples/clash_handling.rs
  examples/consuming_actions.rs
  examples/default_controls.rs
  examples/mouse_motion.rs
  examples/mouse_position.rs
  examples/mouse_wheel.rs
  examples/press_duration.rs
  examples/register_gamepads.rs
  examples/send_actions_over_network.rs
  examples/single_player.rs
  examples/twin_stick_controller.rs
  examples/ui_driven_actions.rs
  src/action_state.rs
  src/axislike.rs
  src/clashing_inputs.rs
  src/input_mocking.rs
  src/input_processing/dual_axis/circle.rs
  src/input_processing/dual_axis/custom.rs
  src/input_processing/dual_axis/mod.rs
  src/input_processing/single_axis/custom.rs
  src/input_processing/single_axis/mod.rs
  src/input_processing/single_axis/range.rs
  src/input_streams.rs
  src/orientation.rs
  src/plugin.rs
  tests/action_diffs.rs
  tests/clashes.rs
  tests/gamepad_axis.rs
  tests/integration.rs
  tests/mouse_motion.rs
  tests/mouse_wheel.rs
  tests/multiple_gamepads.rs
Labels: release

#522 Handle `just_pressed`/`just_released` in the `FixedUpdate` schedule
  RELEASES.md
  benches/action_state.rs
  src/action_state.rs
  src/plugin.rs
  src/systems.rs
  tests/fixed_update.rs
Labels: bug, controversial

#534 Swap to a trait-based architecture for UserInput
  Cargo.toml
  README.md
  RELEASES.md
  examples/action_state_resource.rs
  examples/axis_inputs.rs
  examples/clash_handling.rs
  examples/default_controls.rs
  examples/input_processing.rs
  examples/mouse_motion.rs
  examples/mouse_wheel.rs
  examples/twin_stick_controller.rs
  examples/virtual_dpad.rs
  src/action_state.rs
  src/axislike.rs
  src/buttonlike.rs
  src/clashing_inputs.rs
  src/display_impl.rs
  src/input_map.rs
  src/input_mocking.rs
  src/input_streams.rs
  src/lib.rs
  src/plugin.rs
  src/raw_inputs.rs
  src/user_input.rs
  src/user_input/chord.rs
  src/user_input/gamepad.rs
  src/user_input/keyboard.rs
  src/user_input/mod.rs
  src/user_input/mouse.rs
  tests/clashes.rs
  tests/gamepad_axis.rs
  tests/mouse_motion.rs
  tests/mouse_wheel.rs
Labels: enhancement, usability, performance, controversial

#540 Remove ActionStateDriver
  Cargo.toml
  README.md
  RELEASES.md
  examples/mouse_position.rs
  examples/ui_driven_actions.rs
  src/action_driver.rs
  src/clashing_inputs.rs
  src/lib.rs
  src/plugin.rs
  src/systems.rs
  src/user_input/chord.rs
  src/user_input/gamepad.rs
  src/user_input/keyboard.rs
  src/user_input/mouse.rs
  tests/integration.rs
  tools/ci/src/main.rs
Labels: code-quality, breaking-change

#541 Fix TODO try_apply methods
  src/input_processing/dual_axis/custom.rs
  src/input_processing/single_axis/custom.rs
Labels: bug

#544 Remove orientation module
  RELEASES.md
  src/axislike.rs
  src/lib.rs
  src/orientation.rs
Labels: code-quality, breaking-change

#543 Fix mouse accumulation
  Cargo.toml
  RELEASES.md
  src/action_state.rs
  src/axislike.rs
  src/errors.rs
  src/input_mocking.rs
  src/input_streams.rs
  src/lib.rs
  src/plugin.rs
  src/systems.rs
  src/user_input/chord.rs
  src/user_input/gamepad.rs
  src/user_input/keyboard.rs
  src/user_input/mouse.rs
Labels: bug
