Repository Leafwing-Studios/leafwing-input-manager, pull requests merged in 2025-07, with the labels that each got.

#704 Bump to 0.17.1
  Cargo.toml
  RELEASES.md
  examples/register_gamepads.rs
  examples/twin_stick_controller.rs
  tests/action_diffs.rs
  tests/fixed_update.rs
Labels: release

#669 Introduce boxed methods for insertion.
  RELEASES.md
  src/input_map.rs
Labels: usability

#693 Fixes #612 and `previous_duration`
  src/action_state/mod.rs
Labels: bug
